#!/bin/sh
set -eu

export QEMU_MODULE_DIR=/opt/qemu/usr/lib64/qemu

exec /opt/qemu/lib64/ld-linux-x86-64.so.2 \
  --library-path /opt/qemu/lib64:/opt/qemu/usr/lib64 \
  /opt/qemu/usr/bin/qemu-system-x86_64 \
  -L /opt/qemu/usr/share/qemu \
  "$@"
