#!/bin/sh
set -eu

export QEMU_MODULE_DIR=/opt/qemu/usr/lib/x86_64-linux-gnu/qemu

exec /opt/qemu/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 \
  --library-path /opt/qemu/usr/lib/x86_64-linux-gnu \
  /opt/qemu/usr/bin/qemu-system-x86_64 \
  -L /opt/qemu/usr/share/qemu \
  "$@"
